name: Windows Visual Studio

on: [push, pull_request, workflow_dispatch]

env:
  CMAKE_GENERATOR: Visual Studio 17 2022
  PYTHON_VERSION: Python312
  NJOBS: 4

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: ports\ci\windows-vs\build.bat
    - name: Deploy
      run: ports\ci\windows-vs\deploy.bat
